services:
  server:
    build: .
    command: npm start #pm2-runtime pm2.config.js --watch
    volumes:
      - .:/app/
      - ./node_modules:/app/node_modules
    env_file:
      - .env
    restart: unless-stopped
    networks:
      internal:
    ports:
      - "${PORT}:${PORT}"
networks:
  internal:
